source 'https://rubygems.org/'

gem 'activerecord'
gem 'pg'
gem 'pry-byebug'
gem 'puma'
gem 'rake'
gem 'rest-client'
gem 'rspec'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'tux'
