development:
  adapter: postgresql
  encoding: unicode
  database: clinickr_development
  pool: 5
  host: localhost
  username: clinickr
  password: admin123

test:
  adapter: postgresql
  encoding: unicode
  database: clinickr_test
  pool: 5
  host: localhost
  username: clinickr
  password: admin123
